version: "3.8"

services:
  tgbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: kaljmarik/tgbot
    ports:
      - "8010:8000"  #external:internal
    environment:
      - TELEGRAM_BOT_TOKEN=""
      - TELEGRAM_CHAT_ID=""
    restart: always
    pull_policy: build